In [3]:
import pandas as pd

data= pd.read_csv('titanic_sub.csv')

data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [9]:
import numpy as np
 
file = 'titanic_sub.csv'

text = np.loadtxt(file,delimiter = ',', dtype=str)

print(text)

[['PassengerId' 'Survived' 'Pclass' ... 'Fare' 'Cabin' 'Embarked']
 ['1' '0' '3' ... '7.25' '' 'S']
 ['2' '1' '1' ... '71.2833' 'C85' 'C']
 ...
 ['889' '0' '3' ... '23.45' '' 'S']
 ['890' '1' '1' ... '30.0' 'C148' 'C']
 ['891' '0' '3' ... '7.75' '' 'Q']]


In [10]:
file_2 = 'seaslug.txt'

text = np.loadtxt(file,delimiter = ',',dtype =str)

print(text)

[['PassengerId' 'Survived' 'Pclass' ... 'Fare' 'Cabin' 'Embarked']
 ['1' '0' '3' ... '7.25' '' 'S']
 ['2' '1' '1' ... '71.2833' 'C85' 'C']
 ...
 ['889' '0' '3' ... '23.45' '' 'S']
 ['890' '1' '1' ... '30.0' 'C148' 'C']
 ['891' '0' '3' ... '7.75' '' 'Q']]


In [14]:
file = 'mnist.txt'

text = np.loadtxt(file,
                  delimiter = ',',
                 skiprows =1)

In [15]:
print(text)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 ...
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]]


In [17]:
file = 'text.txt'

In [20]:
file_open = open(file, mode='w')
file_open.close()

In [24]:
file = 'text.txt'

file_open = open(file, 'r')
file_read = file_open.read()

file_open.close()

print(file_read)

This is a text file


This is a text file
